version: "3.9"

services:
  rest:
    build:
      context: ./rest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
